FROM amd64/alpine:3.16
RUN apk upgrade --no-cache && apk add --no-cache openssl
ADD ./package/gogo-server /
ADD ./package/config.json /
ADD ./package/gogo-web /
ENTRYPOINT ["/gogo-server","config.json"]
