FROM amd64/alpine:3.20
RUN apk upgrade --no-cache && apk add --no-cache openssl
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY ./package /app
RUN chown -R appuser:appgroup /app && chmod 0755 /app/gogo-server
WORKDIR /app
USER appuser
ENTRYPOINT ["RUST_LOG=info","./gogo-server","config.json"]
