package yz.gogo.util;

/**
 * Google Domain Utils
 */
public final class GoogleDomainUtils {

    /**
     * Array of domains
     */
    private static final String[] NAMES = new String[]{
            "www.google.is",
            "www.google.dk",
            "www.google.no",
            "www.google.se",
            "www.google.fi",
            "www.google.ee",
            "www.google.lv",
            "www.google.lt",
            "www.google.ie",
            "www.google.co.uk",
            "www.google.gg",
            "www.google.je",
            "www.google.im",
            "www.google.fr",
            "www.google.nl",
            "www.google.be",
            "www.google.lu",
            "www.google.de",
            "www.google.at",
            "www.google.ch",
            "www.google.li",
            "www.google.pt",
            "www.google.es",
            "www.google.com.gi",
            "www.google.ad",
            "www.google.it",
            "www.google.com.mt",
            "www.google.sm",
            "www.google.gr",
            "www.google.ru",
            "www.google.com.by",
            "www.google.com.ua",
            "www.google.pl",
            "www.google.cz",
            "www.google.sk",
            "www.google.hu",
            "www.google.si",
            "www.google.hr",
            "www.google.ba",
            "www.google.me",
            "www.google.rs",
            "www.google.mk",
            "www.google.bg",
            "www.google.ro",
            "www.google.md",
            //"www.google.cn",
            "www.google.mn",
            "www.google.co.kr",
            "www.google.co.jp",
            "www.google.com.vn",
            "www.google.la",
            "www.google.com.kh",
            "www.google.co.th",
            "www.google.com.my",
            "www.google.com.sg",
            "www.google.com.bn",
            "www.google.com.ph",
            "www.google.co.id",
            "www.google.kz",
            "www.google.kg",
            "www.google.com.tj",
            "www.google.co.uz",
            "www.google.tm",
            "www.google.com.af",
            "www.google.com.pk",
            "www.google.com.np",
            "www.google.co.in",
            "www.google.com.bd",
            "www.google.lk",
            "www.google.mv",
            "www.google.com.kw",
            "www.google.com.sa",
            "www.google.com.bh",
            "www.google.ae",
            "www.google.com.om",
            "www.google.jo",
            "www.google.co.il",
            "www.google.com.lb",
            "www.google.com.tr",
            "www.google.az",
            "www.google.am",
            "www.google.co.ls",
            "www.google.com.eg",
            "www.google.com.ly",
            "www.google.dz",
            "www.google.co.ma",
            "www.google.sn",
            "www.google.gm",
            "www.google.ml",
            "www.google.bf",
            "www.google.com.sl",
            "www.google.ci",
            "www.google.com.gh",
            "www.google.tg",
            "www.google.bj",
            "www.google.ne",
            "www.google.com.ng",
            "www.google.sh",
            "www.google.cm",
            "www.google.td",
            "www.google.cf",
            "www.google.ga",
            "www.google.cg",
            "www.google.cd",
            "www.google.it.ao",
            "www.google.com.et",
            "www.google.dj",
            "www.google.co.ke",
            "www.google.co.ug",
            "www.google.co.tz",
            "www.google.rw",
            "www.google.bi",
            "www.google.mw",
            "www.google.co.mz",
            "www.google.mg",
            "www.google.sc",
            "www.google.mu",
            "www.google.co.zm",
            "www.google.co.zw",
            "www.google.co.bw",
            "www.google.com.na",
            "www.google.co.za",
            "www.google.com.au",
            "www.google.com.nf",
            "www.google.co.nz",
            "www.google.com.sb",
            "www.google.com.fj",
            "www.google.fm",
            "www.google.ki",
            "www.google.nr",
            "www.google.tk",
            "www.google.ws",
            "www.google.as",
            "www.google.to",
            "www.google.nu",
            "www.google.co.ck",
            "www.google.com.do",
            "www.google.tt",
            "www.google.com.co",
            "www.google.com.ec",
            "www.google.co.ve",
            "www.google.gy",
            "www.google.com.pe",
            "www.google.com.bo",
            "www.google.com.py",
            "www.google.com.br",
            "www.google.com.uy",
            "www.google.com.ar",
            "www.google.cl",
            "www.google.gl",
            "www.google.ca",
            "www.google.com",
            "www.google.com.mx",
            "www.google.com.gt",
            "www.google.com.bz",
            "www.google.com.sv",
            "www.google.hn",
            "www.google.com.ni",
            "www.google.co.cr",
            "www.google.com.pa",
            "www.google.bs",
            "www.google.com.cu",
            "www.google.com.jm",
            "www.google.ht"};

    /**
     * last UA requested
     */
    private static int INDEX = 0;

    /**
     * Prevent class instances from being created in any place other than this very class.
     */
    private GoogleDomainUtils() {

    }

    /**
     * Get Google domain
     *
     * @return domain string
     */
    public static String get() {
        if (INDEX > NAMES.length - 1) {
            //reset to 0
            INDEX = 0;
        }
        return NAMES[INDEX++];
    }
}